apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubepulse.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kubepulse.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubepulse.fullname" . }}
  labels:
    {{- include "kubepulse.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubepulse.fullname" . }}
  labels:
    {{- include "kubepulse.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubepulse.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubepulse.fullname" . }}
    namespace: {{ .Values.namespace }}
