{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kubepulse.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kubepulse.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kubepulse.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
      path: /metrics
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubepulse.fullname" . }}-metrics
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kubepulse.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "kubepulse.selectorLabels" . | nindent 4 }}
{{- end }}
