services:
  nats:
    image: nats:2-alpine
    command: ["--js", "--sd", "/data", "-m", "8222"]
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats-data:/data
    deploy:
      resources:
        limits:
          memory: 256M

  clickhouse:
    image: clickhouse/clickhouse-server:24-alpine
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ch-data:/var/lib/clickhouse
      - ./migrations:/docker-entrypoint-initdb.d
    environment:
      CLICKHOUSE_DB: kubepulse
      CLICKHOUSE_USER: kubepulse
      CLICKHOUSE_PASSWORD: kubepulse
    deploy:
      resources:
        limits:
          memory: 512M
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--maxmemory", "128mb", "--maxmemory-policy", "allkeys-lru"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    deploy:
      resources:
        limits:
          memory: 192M

volumes:
  nats-data:
  ch-data:
  redis-data:
